const returnDataObj = {
    "property": [
      {
        "id": "1",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "1",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "2",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "2",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "3",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "3",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "4",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "4",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "5",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "5",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "6",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "6",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "7",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "7",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "8",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "8",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "9",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "9",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "10",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "10",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "11",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "11",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "12",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "12",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "13",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "13",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "14",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "14",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "15",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "15",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "16",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "16",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "17",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "17",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "18",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "18",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "19",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "19",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "20",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "20",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "21",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "21",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "22",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "22",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "23",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "23",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "24",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "24",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "25",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "25",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "26",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "26",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "27",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "27",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "28",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "28",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "29",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "29",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "30",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "30",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "31",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "31",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "32",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "32",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "33",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "33",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "34",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "34",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "35",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "35",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "36",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "36",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "37",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "37",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "38",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "38",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "39",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "39",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "40",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "40",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "41",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "41",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "42",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "42",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "43",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "43",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "44",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "44",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "45",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "45",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "46",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "46",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "47",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "47",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "48",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "48",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "49",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "49",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "50",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "50",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "51",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "51",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "52",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "52",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "53",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "53",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "54",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "54",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "55",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "55",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "56",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "56",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "57",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "57",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "58",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "58",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "59",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "59",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "60",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "60",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "61",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "61",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "62",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "62",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "63",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "63",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "64",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "64",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "65",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "65",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "66",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "66",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "67",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "67",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "68",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "68",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "69",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "69",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "70",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "70",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "71",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "71",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "72",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "72",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "73",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "73",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "74",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "74",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "75",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "75",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "76",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "76",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "77",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "77",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "78",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "78",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "79",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "79",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "80",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "80",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "81",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "81",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "82",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "82",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "83",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "83",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "84",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "84",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "85",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "85",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "86",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "86",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "87",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "87",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "88",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "88",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "89",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "89",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "90",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "90",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "91",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "91",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "92",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "92",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "93",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "93",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "94",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "94",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "95",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "95",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "96",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "96",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "97",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "97",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "98",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "98",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "99",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "99",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "100",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "100",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "101",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "101",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "102",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "102",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "103",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "103",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "104",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "104",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "105",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "105",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "106",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "106",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "107",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "107",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "108",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "108",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "109",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "109",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "110",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "110",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "111",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "111",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "112",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "112",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "113",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "113",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "114",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "114",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "115",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "115",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "116",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "116",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "117",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "117",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "118",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "118",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "119",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "119",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "120",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "120",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "121",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "121",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "122",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "122",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "123",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "123",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "124",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "124",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "125",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "125",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "126",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "126",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "127",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "127",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "128",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "128",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "129",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "129",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "130",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "130",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "131",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "131",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "132",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "132",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "133",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "133",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "134",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "134",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "135",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "135",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "136",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "136",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "137",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "137",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "138",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "138",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "139",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "139",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "140",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "140",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "141",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "141",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "142",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "142",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "143",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "143",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "144",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "144",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "145",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "145",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "146",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "146",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "147",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "147",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "148",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "148",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "149",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "149",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "150",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "150",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "151",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "151",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "152",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "152",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "153",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "153",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "154",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "154",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "155",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "155",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "156",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "156",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "157",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "157",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "158",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "158",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "159",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "159",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "160",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "160",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "161",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "161",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "162",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "162",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "163",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "163",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "164",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "164",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "165",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "165",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "166",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "166",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "167",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "167",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "168",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "168",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "169",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "169",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "170",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "170",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "171",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "171",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "172",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "172",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "173",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "173",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "174",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "174",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "175",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "175",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "176",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "176",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "177",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "177",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "178",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "178",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "179",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "179",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "180",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "180",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "181",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "181",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "182",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "182",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "183",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "183",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "184",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "184",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "185",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "185",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "186",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "186",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "187",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "187",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "188",
        "area": "Westchester County",
        "address": "62 Highland St, Eastchester, NY 10608",
        "city": "Eastchester",
        "image": "188",
        "type": "Single Family",
        "floorspace": "1264",
        "beds": "4",
        "baths": "1",
        "price": "325000",
        "parking": "",
        "construction": "basement,landry"
    },
    {
        "id": "189",
        "area": "Westchester County",
        "address": "33 Alden Pl, Bronxville, NY 10708",
        "city": "Bronxville",
        "image": "189",
        "type": "Townhouse",
        "floorspace": "1074",
        "beds": "3",
        "baths": "1",
        "price": "665000",
        "parking": "",
        "construction": "fireplace,gym"
    },
    {
        "id": "190",
        "area": "Westchester County",
        "address": "261 California rd, Mamaroneck, NY 10612",
        "city": "Mamaroneck",
        "image": "190",
        "type": "Studio",
        "floorspace": "700",
        "beds": "1",
        "baths": "1",
        "price": "265000",
        "parking": "1",
        "construction": "landry,gym"
    },
    {
        "id": "191",
        "area": "Westchester County",
        "address": "23 Isle Lane, New Rochelle, NY 10538",
        "city": "New Rochelle",
        "image": "191",
        "type": "Multi Family",
        "floorspace": "1630",
        "beds": "3",
        "baths": "2",
        "price": "765000",
        "parking": "3",
        "construction": "basement,fireplace"
    },
    {
        "id": "192",
        "area": "Westchester County",
        "address": "95 Vernon ave, Scarsdale, NY 10538",
        "city": "Scarsdale",
        "image": "192",
        "type": "Studio",
        "floorspace": "1200",
        "beds": "1",
        "baths": "1",
        "price": "215000",
        "parking": "3",
        "construction": "elevator,garage"
    },
    {
        "id": "193",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "193",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "194",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "194",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "195",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "195",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "196",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "196",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    },
    {
        "id": "197",
        "area": "Westchester County",
        "address": "321 Munday Lane, Eastchester, NY 10606",
        "city": "Eastchester",
        "image": "197",
        "type": "Multi Family",
        "floorspace": "2100",
        "beds": "3",
        "baths": "1",
        "price": "845000",
        "parking": "3",
        "construction": "basement,pool"
    },
    {
        "id": "198",
        "area": "Westchester County",
        "address": "123 Ducksworth Way, New Rochelle, NY 10535",
        "city": "New Rochelle",
        "image": "198",
        "type": "Single Family",
        "floorspace": "2300",
        "beds": "2",
        "baths": "1",
        "price": "650000",
        "parking": "3",
        "construction": "garage,landry"
    },
    {
        "id": "199",
        "area": "Westchester County",
        "address": "6 Garth rd, Scarsdale, NY 10583",
        "city": "Scarsdale",
        "image": "199",
        "type": "Duplex",
        "floorspace": "1264",
        "beds": "3",
        "baths": "1",
        "price": "295000",
        "parking": "2",
        "construction": "fireplace,landry"
    },
    {
        "id": "200",
        "area": "Westchester County",
        "address": "39 Sterling ave, White Plains, NY 10606",
        "city": "White Plains",
        "image": "200",
        "type": "Condo",
        "floorspace": "768",
        "beds": "2",
        "baths": "2",
        "price": "445000",
        "parking": "1",
        "construction": "elevator,garage"
    }
          
      ]
  }

  let queriedDataArray;
  let queryConditionArray = [];
  let middleItemID=35;
  
  for (let i=1;i<120;i++)
  queryConditionArray.push(i.toString());

console.log(queryConditionArray);
queriedDataArray = returnDataObj.property.filter((val) => {
  console.log(queryConditionArray.indexOf(val.id)); 
if (queryConditionArray.indexOf(val.id)>=0) {   
     return val;
    }
});



console.log(`queriedDataArray`,queriedDataArray);